/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sanbit.android.mystats;

public final class R {
    public static final class array {
        public static final int alarm_options=0x7f050002;
        public static final int alarm_options_values=0x7f050003;
        public static final int report_interval=0x7f050000;
        public static final int sort_contact_order=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int alarm22=0x7f020000;
        public static final int alarm32=0x7f020001;
        public static final int alert=0x7f020002;
        public static final int alti48=0x7f020003;
        public static final int clock48=0x7f020004;
        public static final int comp48=0x7f020005;
        public static final int folder48=0x7f020006;
        public static final int globe48=0x7f020007;
        public static final int group48=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int network48=0x7f02000a;
        public static final int personal=0x7f02000b;
        public static final int prefs48=0x7f02000c;
        public static final int sanbit=0x7f02000d;
    }
    public static final class id {
        public static final int about=0x7f060013;
        public static final int active=0x7f060002;
        public static final int alarm_status=0x7f060025;
        public static final int alarms=0x7f060012;
        public static final int alert=0x7f060024;
        public static final int call_date=0x7f060006;
        public static final int call_frequency=0x7f060027;
        public static final int call_number=0x7f060004;
        public static final int call_value=0x7f060005;
        public static final int communication=0x7f06001e;
        public static final int confirm=0x7f060017;
        public static final int contact_row=0x7f060007;
        public static final int contacts=0x7f060010;
        public static final int create_account=0x7f06000e;
        public static final int email=0x7f06000b;
        public static final int fail_reason=0x7f060009;
        public static final int five_days=0x7f06001b;
        public static final int frequency_list=0x7f060028;
        public static final int image=0x7f060022;
        public static final int interval=0x7f060003;
        public static final int login_reason=0x7f060016;
        public static final int logout=0x7f06001d;
        public static final int manually=0x7f06001c;
        public static final int name=0x7f060000;
        public static final int no_communication=0x7f060026;
        public static final int online=0x7f060015;
        public static final int password=0x7f06000c;
        public static final int password_confirm=0x7f06000d;
        public static final int preferences=0x7f060011;
        public static final int report_interval=0x7f060020;
        public static final int reports=0x7f06000f;
        public static final int sort_order=0x7f060008;
        public static final int status=0x7f060001;
        public static final int sync=0x7f060014;
        public static final int talk_time=0x7f060029;
        public static final int talk_time_list=0x7f06002a;
        public static final int text1=0x7f060021;
        public static final int three_days=0x7f06001a;
        public static final int title=0x7f06001f;
        public static final int title1=0x7f060023;
        public static final int upload_daily=0x7f060019;
        public static final int upload_interval=0x7f060018;
        public static final int username=0x7f06000a;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int alarm_row=0x7f030001;
        public static final int call_history=0x7f030002;
        public static final int contacts_activity=0x7f030003;
        public static final int contacts_list=0x7f030004;
        public static final int create_account=0x7f030005;
        public static final int home=0x7f030006;
        public static final int login=0x7f030007;
        public static final int main=0x7f030008;
        public static final int manage_alarm_activity=0x7f030009;
        public static final int preference=0x7f03000a;
        public static final int recent_communication=0x7f03000b;
        public static final int report=0x7f03000c;
        public static final int reports_row=0x7f03000d;
        public static final int user_report=0x7f03000e;
    }
    public static final class string {
        public static final int about=0x7f04001c;
        public static final int about_text=0x7f04001d;
        public static final int alarm_list=0x7f04001b;
        public static final int app_name=0x7f040000;
        public static final int body=0x7f040003;
        public static final int call_frequency=0x7f040014;
        public static final int call_talk_time=0x7f040015;
        public static final int confirm=0x7f040004;
        public static final int contacts_activity=0x7f040012;
        public static final int create_account=0x7f040016;
        public static final int edit_alarm=0x7f040018;
        public static final int everyday=0x7f04000a;
        public static final int five_days=0x7f04000c;
        public static final int home_activity=0x7f040001;
        public static final int login=0x7f040011;
        public static final int manually=0x7f04000d;
        public static final int menu_upload_file=0x7f040006;
        public static final int mystats=0x7f04000e;
        public static final int password=0x7f040008;
        public static final int preference=0x7f040013;
        public static final int recent_activity=0x7f040005;
        public static final int report_activity=0x7f04000f;
        public static final int reports_activity=0x7f040019;
        public static final int sort_order=0x7f040017;
        public static final int three_days=0x7f04000b;
        public static final int time_interval=0x7f04001a;
        public static final int title=0x7f040002;
        public static final int upload_interval=0x7f040009;
        public static final int user_report=0x7f040010;
        public static final int username=0x7f040007;
    }
}
